# Generated by Django 5.2.7 on 2025-10-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coreBD', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('ocupation', models.CharField(max_length=20)),
                ('collage_level', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=150, null=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_docent', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreBD.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=50)),
                ('birthDate', models.CharField(max_length=40)),
                ('bapDiag', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('commune', models.CharField(max_length=40)),
                ('grade', models.CharField(max_length=40)),
                ('etnia', models.CharField(blank=True, max_length=40, null=True)),
                ('fk_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreBD.curso')),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreBD.nivel')),
                ('fk_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersManager.studentparent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
