# Generated by Django 5.2.7 on 2025-10-22 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('active', models.BooleanField()),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersManager.category')),
                ('fk_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersManager.rol')),
            ],
        ),
    ]
