# Generated by Django 5.2.7 on 2025-10-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='UserCategory',
        ),
    ]
