# Generated by Django 5.2.7 on 2025-10-25 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersManager', '0002_rename_category_usercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('ocupation', models.CharField(max_length=20)),
                ('collage_level', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=50)),
                ('birthDate', models.CharField(max_length=40)),
                ('bapDiag', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('commune', models.CharField(max_length=40)),
                ('grade', models.CharField(max_length=40)),
                ('etnia', models.CharField(blank=True, max_length=40, null=True)),
                ('fk_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersManager.studentparent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
