# Generated by Django 5.2.7 on 2025-10-26 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreBD', '0002_rol'),
        ('usersManager', '0003_studentparent_user_createdat_user_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fk_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreBD.rol'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
