# Generated by Django 5.2.7 on 2025-10-27 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersManager', '0004_alter_user_fk_rol_delete_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='fk_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersManager.rol'),
        ),
    ]
