# Generated by Django 5.2.7 on 2025-10-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreBD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
    ]
