# Generated by Django 5.2.7 on 2025-10-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreBD', '0002_rol'),
        ('usersManager', '0005_rol_alter_user_fk_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
