# Generated by Django 5.2.7 on 2025-10-31 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreBD', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('ocupation', models.CharField(max_length=20)),
                ('collage_level', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=50)),
                ('birthDate', models.CharField(max_length=40)),
                ('bapDiag', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('commune', models.CharField(max_length=40)),
                ('grade', models.CharField(max_length=40)),
                ('etnia', models.CharField(blank=True, max_length=40, null=True)),
                ('fk_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coreBD.curso')),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreBD.nivel')),
                ('fk_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentAppManager.studentparent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
